name: sky130hd_temp-sense-generator

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  sky130hd_temp:
    runs-on: ubuntu-latest
    steps:

      - name: Clone OpenFASOC repo
        run: |
          mkdir /home/runner/work/openfasoc_ci && cd $!
          git clone https://github.com/saicharan0112/OpenFASOC && cd OpenFASOC

      - name: Run tempSense generator
        env:
                IMAGE_NAME: ghcr.io/saicharan0112/openfasoc_ci_image:alpha
        run: |
          echo $PWD
          ls -al
          touch file.log
          docker run --rm \
            -v $PWD:$PWD\
            -w $PWD\
            $IMAGE_NAME\
            bash -c "\
              pip3 install -r requirements.txt &&\
              cd ./openfasoc/generators/temp-sense-gen &&\
              make sky130hd_temp\
            "| tee -a file.log
          if grep "\[ERROR\]" file.log; then exit 1; else exit 0; fi         

      - name: Pack the output and store it inside this repo
        run: |
          cd /home/runner/work/ && mkdir data

      - name: Commit and push changes
        run: |
          cp /home/runner/work/openfasoc_ci/openfasoc/generators/temp-sense-gen/work /home/runner/work/OpenFASOC-CI-simulations/OpenFASOC-CI-simulations/.
          git status
          git config --global user.name 'sai charan'
          git config --global user.email 'saicharan0112@users.noreply.github.com'
          git add -A 
          git commit -m "add run data"
          git push