name: sky130hd_temp-sense-generator

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  sky130hd_temp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout saicharan0112/OpenFASOC master branch
        uses: actions/checkout@v3
        with:
          repository: saicharan0112/OpenFASOC
          ref: main

      - name: Run tempSense generator
        env:
                IMAGE_NAME: ghcr.io/saicharan0112/openfasoc_ci_image:alpha
        run: |
          touch file.log
          docker run --rm \
            -v $PWD:$PWD\
            -w $PWD\
            $IMAGE_NAME\
            bash -c "\
              pip3 install -r requirements.txt &&\
              cd ./openfasoc/generators/temp-sense-gen &&\
              make sky130hd_temp\
            "| tee -a file.log
          if grep "\[ERROR\]" file.log; then exit 1; else exit 0; fi         

      - name: Pack the output and store it inside this repo
        run: |
          cd /home/runner/work/ && mkdir data
          cp -rf /home/runner/work/OpenFASOC-CI-simulations/OpenFASOC-CI-simulations/openfasoc/generators/temp-sense-gen/simulations/run/* /home/runner/work/data/.
          cp -rf /home/runner/work/OpenFASOC-CI-simulations/OpenFASOC-CI-simulations/openfasoc/generators/temp-sense-gen/work /home/runner/work/data/.
          rm -rf /home/runner/work/OpenFASOC-CI-simulations/OpenFASOC-CI-simulations/*
          cp -rf data /home/runner/work/OpenFASOC-CI-simulations/OpenFASOC-CI-simulations/.

      - name: Commit and push changes
        run: |
          git status
          git config --global user.name 'sai charan'
          git config --global user.email 'saicharan0112@users.noreply.github.com'
          git add -A 
          git commit -m "add run data"
          git push